---
title: "git_00"
author: "Kevin Brandon Salazar"
date: "Year 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!--> ’Twas brillig, and the slithy toves  
  Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
  And the mome raths outgrabe.  
“Beware the Jabberwock, my son!

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->  
Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright —  
And this was odd, because it was  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done —  
"It's very rude of him," she said,  
"To come and spoil the fun."  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
I love to code in R  
It makes me feel like a star  
I can manipulate data frames  
And give them fancy names  

I can run all kinds of tests  
And plot the results with ggplot2  
I can use tidyverse and dplyr  
And make my code cleaner and faster  

I can write functions and loops  
And avoid all kinds of bugs  
I can use R Markdown and Shiny  
And make my reports interactive and shiny  

I can learn from many packages  
And join the R community  
I can share my code on GitHub  
And get feedback from other R lovers  

R is more than a language  
It is a way of thinking  
R is more than a tool  
It is a source of joy  